server:
  port: 8080

spring:
  application:
    name: MyArgus

#  sql:
#    init:
#      mode: always
#      continue-on-error: false
#      schema-locations:
#        - classpath:sql/schema_temp.sql

  datasource:
    url: jdbc:postgresql://localhost:12138/argus
    username: "jin"
    password: "021799"
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler